#ifdef CHRONOS_IMPLEMENTATION
#define CR_VM_IMPLEMENTATION
#define CR_PARSER_IMPLEMENTATION
#define CR_OP_REGISTRY_IMPLEMENTATION
#define CR_UTILS_IMPLEMENTATION
#define CR_DSP_IMPLEMENTATION

#include "cr_parser.h"

#endif
